receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Host metrics
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:

processors:
  # Basic processing
  batch:
    timeout: 1s
    send_batch_size: 1024

  # Resource detection
  resourcedetection:
    detectors: [env, system]
    timeout: 5s

  # Memory limiter
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  # Transform processor to fix OpenTelemetry log compatibility with Elasticsearch
  transform:
    log_statements:
      - context: resource
        statements:
          # Flatten nested executable object to string
          - set(attributes["process.executable.path"], attributes["process.executable"]["path"]) where attributes["process.executable"] != nil
          - delete_key(attributes, "process.executable") where attributes["process.executable"] != nil

exporters:
  # Prometheus metrics export
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Tempo traces export
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  # Elasticsearch logs export - Using data streams for better log management
  elasticsearch:
    endpoints: [http://elasticsearch:9200]
    logs_index: "logs-otel-default"
    mapping:
      mode: "none"
    # Flatten resource and scope attributes for better compatibility
    logs_dynamic_index:
      enabled: false

  # For debugging, we'll keep debug exporter too
  debug:
    verbosity: detailed

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1888

service:
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlp/tempo, debug]

    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, transform, batch]
      exporters: [elasticsearch, debug]

  telemetry:
    logs:
      level: "info"
    metrics:
      level: basic
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
