# Prometheus Production Configuration Example
# Copy this to prometheus.yml and customize for your environment

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'production'
    environment: 'prod'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      scheme: http
      timeout: 10s
      api_version: v2

# Rules files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Java applications
  - job_name: 'java-apps'
    static_configs:
      - targets: ['collections-spring:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: false
    honor_timestamps: true
    
    # Custom labels for better organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):\d+'
        replacement: '${1}'
      - target_label: service
        replacement: 'collections-spring'
      - target_label: team
        replacement: 'platform'

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):\d+'
        replacement: '${1}'

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    
    # Filter out high-cardinality labels
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: service
      - regex: 'container_label_com_docker_compose_.*'
        action: labeldrop

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s
    metrics_path: /metrics

  # AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Additional service discovery for production
  # - job_name: 'kubernetes-pods'
  #   kubernetes_sd_configs:
  #     - role: pod
  #   relabel_configs:
  #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
  #       action: keep
  #       regex: true

# Storage configuration for production
# storage:
#   tsdb:
#     path: /prometheus/data
#     retention.time: 30d
#     retention.size: 50GB
#     min-block-duration: 2h
#     max-block-duration: 25h
#   remote_write:
#     - url: "https://your-prometheus-remote-storage/api/v1/write"
#       basic_auth:
#         username: "user"
#         password: "password"

# Federation for multi-cluster setup
# - job_name: 'federate'
#   scrape_interval: 15s
#   honor_labels: true
#   metrics_path: '/federate'
#   params:
#     'match[]':
#       - '{job=~"prometheus|node-exporter|cadvisor"}'
#   static_configs:
#     - targets:
#       - 'prometheus-cluster-1:9090'
#       - 'prometheus-cluster-2:9090'