global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@localhost'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'null'

receivers:
  - name: 'null'
